# Generated by Django 2.0.2 on 2019-08-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190802_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file_type',
            new_name='audio_file',
        ),
    ]
